[project]
name = 'VerifyStack'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.IdentityGuard]
path = 'contracts/IdentityGuard.clar'
clarity_version = 2
epoch = 2.5

[contracts.audit-logger]
path = 'contracts/audit-logger.clar'
clarity_version = 2
epoch = 2.5

[contracts.role-manager]
path = 'contracts/role-manager.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
